all:
  is_secure: true
  credentials: [[ administrateur, redacteur, utilisateur, referent, validateur ]]
xls:
  credentials: [[ administrateur, redacteur, utilisateur, referent, validateur ]]
  is_secure: true
delete:
  credentials: [[ administrateur, redacteur, referent, validateur ]]
  is_secure: true
save:
  credentials: [[ administrateur, redacteur, referent, validateur ]]
  is_secure: true
validate:
  credentials: [[ administrateur, redacteur, referent, validateur ]]
  is_secure: true
deleteZp:
  credentials: [[ administrateur, redacteur, referent, validateur ]]
  is_secure: true
saveZp:
  credentials: [[ administrateur, redacteur, referent, validateur ]]
  is_secure: true
uploadFileGpx:
  credentials: [[ administrateur, redacteur, referent, validateur ]]
  is_secure: true