indexFsSuccess:
  stylesheets:    
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css 
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - superboxselect.css
    - rowActions.css 
    - main.css
    - geoportail.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/lib/Firebug/firebug.js
    - client/mfbase/proj4js/lib/proj4js.js
    - client/mfbase/openlayers/OpenLayers.js
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - client/mfbase/mapfish/lang/fr.js
    - config.js
    - configmap.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.grid.RowActions.js
    - Ext.ux.grid.RowEditor.js
    - Ext.ux.plugins.ProportionalWindows.js
    - Ext.ux.Toast.js
    - Ext.ux.GpsLocation.js
    - RowExpander.js
    - BufferView.js
    - CheckColumn.js
    - SuperBoxSelect.js
    - mapfish.ux.Searcher.Form.Ext.js
    - mapfish.ux.widgets.print.PrintAction.js
    - fs/application.fs.js
    - fs/application.fs.layout.js
    - fs/application.fs.search.js
    - fs/application.fs.stationPanel.js
    - fs/application.fs.editStation.js
    - fs/application.fs.layerWindowFactory.js
    - fs/application.fs.rechercheAvancee.js