matrix:
  include:
    - language: python
      python:
        - "3.5"
      before_install:
        - sudo apt-get install -y libgdal1-dev libgdal-dev
        - sudo apt-get install -y python-gdal

      # install dependencies
      install:
        - cd backend
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
        - cd tests/travis_test
        - ./travis_test.sh

      script:
        -  # test backend
        - cd ../backend
        # - pytest
        # génération de la doc
        - cd ../docs
        - make html
    - language: node-js
      node_js:
        - "9.11.2"
      install:
        - cd ../frontend
        - npm install
      script:
        - npm run compodoc

# deploy github pages on commit on master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # set in the Travis dashboard
  local_dir: docs/build/html
  on:
    branch: master

notifications:
  email:
    recipients:
      - geonature@ecrins-parcnational.fr
    on_failure: never
    on_success: never
