all:
  is_secure: true
  credentials: [[ administrateur, redacteur, utilisateur, referent ]]
cf:
  credentials: [[ administrateur, redacteur ]]
  is_secure: true
invertebre:
  credentials: [[ administrateur, redacteur ]]
  is_secure: true
mortalite:
  credentials: [[ administrateur, redacteur ]]
  is_secure: true