all:
  is_secure: true
  credentials: [[ administrateur, redacteur, utilisateur, referent, validateur ]]
cf:
  credentials: [[ administrateur, redacteur, validateur ]]
  is_secure: true
invertebre:
  credentials: [[ administrateur, redacteur, validateur ]]
  is_secure: true
mortalite:
  credentials: [[ administrateur, redacteur, validateur ]]
  is_secure: true
cflore:
  credentials: [[ administrateur, validateur , redacteur]]
  is_secure: true