indexSynthese:
  credentials: [[ administrateur, redacteur ]]
  is_secure: true
indexCf:
  credentials: [[ administrateur, redacteur ]]
  is_secure: true
indexInvertebre:
  credentials: [[ administrateur, redacteur ]]
  is_secure: true
indexMortalite:
  credentials: [[ administrateur, redacteur ]]
  is_secure: true
index:
  credentials: [[ administrateur, redacteur ]]
  is_secure: true