loginSuccess:
  stylesheets: 
    - bootstrap/css/bootstrap.css
    - login.css

indexSuccess:
  stylesheets: 
    - bootstrap/css/bootstrap.css
    - flot.css
    - main.css
    - morris.css
    - "http://cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.min.css"
  javascripts:
    - "http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"
    - "http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.2/raphael-min.js"
    # - "http://cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.min.js"
    - client/mfbase/morris/morris.min.js
    - statff.js
    - config.js 