loginSuccess:
  stylesheets: 
    - bootstrap/css/bootstrap.css
    - login.css

indexSuccess:
  stylesheets: 
    - bootstrap/css/bootstrap.css
    - flot.css
    - main.css
    - morris.css
    - "http://cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.min.css"
  javascripts:
    - "http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"
    - "http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.2/raphael-min.js"
    # - "http://cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.min.js"
    - client/mfbase/morris/morris.min.js
    - statff.js
    - config.js
    
indexExportSuccess:
  stylesheets: 
    - bootstrap/css/bootstrap.css
    - main.css
    - morris.css
    - "http://cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.min.css"
  javascripts:
    - "http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"
    - "http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.2/raphael-min.js"
    # - "http://cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.min.js"
    - client/mfbase/morris/morris.min.js
    - statff.js
    - config.js

indexSyntheseSuccess:
  stylesheets:
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - main.css
    - superboxselect.css
    - geoportail.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/OpenLayers.js
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - config.js
    - configmap.js
    - accents.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.Toast.js
    - Ext.ux.GpsLocation.js
    - Ext.ux.plugins.ProportionalWindows.js
    - mapfish.ux.Searcher.Form.Ext.js
    - SuperBoxSelect.js
    - RowExpander.js
    - FileDownloader.js
    - FileUploadField.js
    - BufferView.js
    - synthese/application.synthese.js
    - synthese/application.synthese.layout.js
    - synthese/application.synthese.layerWindowFactory.js
    - synthese/application.synthese.search.js
    - synthese/application.synthese.editCf.js
    - synthese/application.synthese.editCflore.js
    - synthese/application.synthese.editInvertebre.js
    - synthese/application.synthese.editMortalite.js
    
indexCfSuccess:
  stylesheets:
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - main.css
    - superboxselect.css
    - geoportail.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/OpenLayers.js
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - client/mfbase/mapfish/lang/fr.js
    - config.js
    - configmap.js
    - accents.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.Toast.js
    - Ext.ux.GpsLocation.js
    - SuperBoxSelect.js
    - cf/application.cf.js
    - cf/application.cf.layerWindowFactory.js
    - cf/application.cf.editFiche.js 

indexCfloreSuccess:
  stylesheets:
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - main.css
    - superboxselect.css
    - geoportail.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/OpenLayers.js
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - client/mfbase/mapfish/lang/fr.js
    - config.js
    - configmap.js
    - accents.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.Toast.js
    - Ext.ux.GpsLocation.js
    - SuperBoxSelect.js
    - cflore/application.cflore.js
    - cflore/application.cflore.layerWindowFactory.js
    - cflore/application.cflore.editFiche.js     
    
indexMortaliteSuccess:
  stylesheets:
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - main.css
    - superboxselect.css
    - geoportail.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/OpenLayers.js
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - client/mfbase/mapfish/lang/fr.js
    - config.js
    - configmap.js
    - accents.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.Toast.js
    - Ext.ux.GpsLocation.js
    - SuperBoxSelect.js
    - cf/application.cf.js
    - cf/application.cf.layerWindowFactory.js
    - cf/application.cf.editFicheMortalite.js
    
indexInvertebreSuccess:
  stylesheets:
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - main.css
    - superboxselect.css
    - geoportail.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/OpenLayers.js
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - client/mfbase/mapfish/lang/fr.js
    - config.js
    - configmap.js
    - accents.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.Toast.js
    - Ext.ux.GpsLocation.js
    - SuperBoxSelect.js
    - invertebre/application.invertebre.js
    - invertebre/application.invertebre.layerWindowFactory.js
    - invertebre/application.invertebre.editFiche.js

indexFpSuccess:
  stylesheets:    
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css 
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - superboxselect.css
    - rowActions.css 
    - main.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/lib/Firebug/firebug.js
#---------Version API IGN 1.2------------------------------
    - client/mfbase/openlayers/OpenLayers.js       
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - client/mfbase/mapfish/lang/fr.js
    - config.js
    - configmap.js
    - Ext.ux.Toast.js
    - mapfish.ux.Searcher.Form.Ext.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.grid.RowActions.js
    - Ext.ux.plugins.ProportionalWindows.js
    - mapfish.ux.widgets.print.PrintAction.js
    - RowExpander.js
    - CheckColumn.js
    - SuperBoxSelect.js
    - FileUploadField.js
    - fp/application.pda.js
    - fp/application.pda.layout.js
    - fp/application.pda.search.js
    - fp/application.pda.zpPanel.js
    - fp/application.pda.editZp.js
    - fp/application.pda.editAp.js
    - fp/application.pda.layerWindowFactory.js
    - fp/application.pda.rechercheAvancee.js

indexFsSuccess:
  stylesheets:    
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css 
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - superboxselect.css
    - rowActions.css 
    - main.css
    - geoportail.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/lib/Firebug/firebug.js
    - client/mfbase/proj4js/lib/proj4js.js
    - client/mfbase/openlayers/OpenLayers.js
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - client/mfbase/mapfish/lang/fr.js
    - config.js
    - configmap.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.grid.RowActions.js
    - Ext.ux.grid.RowEditor.js
    - Ext.ux.plugins.ProportionalWindows.js
    - Ext.ux.Toast.js
    - Ext.ux.GpsLocation.js
    - RowExpander.js
    - BufferView.js
    - CheckColumn.js
    - SuperBoxSelect.js
    - mapfish.ux.Searcher.Form.Ext.js
    - mapfish.ux.widgets.print.PrintAction.js
    - fs/application.fs.js
    - fs/application.fs.layout.js
    - fs/application.fs.search.js
    - fs/application.fs.stationPanel.js
    - fs/application.fs.editStation.js
    - fs/application.fs.layerWindowFactory.js
    - fs/application.fs.rechercheAvancee.js

indexBryoSuccess:
  stylesheets:    
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css 
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - superboxselect.css
    - rowActions.css 
    - main.css
    - geoportail.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/lib/Firebug/firebug.js
    - client/mfbase/proj4js/lib/proj4js.js
    - client/mfbase/openlayers/OpenLayers.js
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - client/mfbase/mapfish/lang/fr.js
    - config.js
    - configmap.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.grid.RowActions.js
    - Ext.ux.grid.RowEditor.js
    - Ext.ux.plugins.ProportionalWindows.js
    - Ext.ux.Toast.js
    - Ext.ux.GpsLocation.js
    - RowExpander.js
    - BufferView.js
    - CheckColumn.js
    - SuperBoxSelect.js
    - mapfish.ux.Searcher.Form.Ext.js
    - mapfish.ux.widgets.print.PrintAction.js
    - bryo/application.bryo.js
    - bryo/application.bryo.layout.js
    - bryo/application.bryo.search.js
    - bryo/application.bryo.stationPanel.js
    - bryo/application.bryo.editStation.js
    - bryo/application.bryo.layerWindowFactory.js
    - bryo/application.bryo.rechercheAvancee.js