indexInvertebreSuccess:
  stylesheets:
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - main.css
    - superboxselect.css
    - geoportail.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/OpenLayers.js
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - client/mfbase/mapfish/lang/fr.js
    - config.js
    - configmap.js
    - accents.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.Toast.js
    - Ext.ux.GpsLocation.js
    - SuperBoxSelect.js
    - invertebre/application.invertebre.js
    - invertebre/application.invertebre.layerWindowFactory.js
    - invertebre/application.invertebre.editFiche.js