all:
  is_secure: true
  credentials: [[ administrateur, redacteur, utilisateur, referent ]]
xls:
  credentials: [[ administrateur, redacteur, referent ]]
  is_secure: true
delete:
  credentials: [[ administrateur, redacteur, referent ]]
  is_secure: true
deleteTaxon:
  credentials: [[ administrateur, redacteur, referent ]]
  is_secure: true
saveTaxon:
  credentials: [[ administrateur, redacteur, referent ]]
  is_secure: true
save:
  credentials: [[ administrateur, redacteur, referent ]]
  is_secure: true