all:
  credentials: [[ administrateur, redacteur, utilisateur, referent ]]
  is_secure: true
save:
  credentials: [[ administrateur, redacteur, referent ]]
  is_secure: true
delete:
  credentials: [[ administrateur, redacteur, referent ]]
  is_secure: true
validate:
  credentials: [[ administrateur, redacteur, referent ]]
  is_secure: true