indexFpSuccess:
  stylesheets:    
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css 
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - superboxselect.css
    - rowActions.css 
    - main.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/lib/Firebug/firebug.js
#---------Version API IGN 1.2------------------------------
    - client/mfbase/openlayers/OpenLayers.js       
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - client/mfbase/mapfish/lang/fr.js
    - config.js
    - configmap.js
    - Ext.ux.Toast.js
    - mapfish.ux.Searcher.Form.Ext.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.grid.RowActions.js
    - Ext.ux.plugins.ProportionalWindows.js
    - mapfish.ux.widgets.print.PrintAction.js
    - RowExpander.js
    - CheckColumn.js
    - SuperBoxSelect.js
    - FileUploadField.js
    - fp/application.pda.js
    - fp/application.pda.layout.js
    - fp/application.pda.search.js
    - fp/application.pda.zpPanel.js
    - fp/application.pda.editZp.js
    - fp/application.pda.editAp.js
    - fp/application.pda.layerWindowFactory.js
    - fp/application.pda.rechercheAvancee.js