indexSyntheseSuccess:
  stylesheets:
    - ../js/client/mfbase/ext-3.4.0/resources/css/ext-all.css
    - ../js/client/mfbase/ext-3.4.0/resources/css/xtheme-gray.css
    - main.css
    - superboxselect.css
    - geoportail.css
  javascripts:
    - client/mfbase/ext-3.4.0/adapter/ext/ext-base.js
    - client/mfbase/ext-3.4.0/ext-all.js
    - client/mfbase/ext-3.4.0/src/locale/ext-lang-fr.js
    - client/mfbase/openlayers/OpenLayers.js
    - client/mfbase/openlayers/lib/OpenLayers/Lang/fr.js
    - client/mfbase/GeoportalMin.js
    - client/mfbase/mapfish/MapFish-all-min.js
    - config.js
    - configmap.js
    - accents.js
    - Ext.ux.form.TwinTriggerComboBox.js
    - Ext.ux.Toast.js
    - Ext.ux.GpsLocation.js
    - Ext.ux.plugins.ProportionalWindows.js
    - mapfish.ux.Searcher.Form.Ext.js
    - SuperBoxSelect.js
    - RowExpander.js
    - FileDownloader.js
    - FileUploadField.js
    - BufferView.js
    - synthese/application.synthese.js
    - synthese/application.synthese.layout.js
    - synthese/application.synthese.layerWindowFactory.js
    - synthese/application.synthese.search.js
    - synthese/application.synthese.editCf.js
    - synthese/application.synthese.editCflore.js
    - synthese/application.synthese.editInvertebre.js
    - synthese/application.synthese.editMortalite.js